# Generated by Django 5.0.1 on 2025-11-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("partner", "Partner"),
                            ("internal", "Internal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="professiona_email_a8dc70_idx"),
                    models.Index(fields=["phone"], name="professiona_phone_b453ec_idx"),
                    models.Index(
                        fields=["source"], name="professiona_source_a9f17e_idx"
                    ),
                ],
            },
        ),
    ]
