# Generated by Django 5.0.1 on 2025-11-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
